languageCode = "en-us"
title = "Enigma"
baseURL = "http://mec-enigma.github.io/"
theme = "dopetrope"

[params.portfolio]
    title = "Projects"
    foldername = "projects"
    findoutmoretext = "Find out more"

[params.blog]
    title = "Blog"
    viewalltext = "View All"
    foldername = "blog"